//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int ID { get; set; }
        public string ordername { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string confirmation_number { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> payment_id { get; set; }
    
        public virtual order_details order_details { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual user user { get; set; }
    }
}
