//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeModel
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class product
    {
        public int ID { get; set; }
        public string prd_name { get; set; }
        public Nullable<int> prd_quantity { get; set; }
        public string price { get; set; }
        public string prd_desc { get; set; }
        public string prd_img { get; set; }
        public Nullable<int> Categ_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> brnd_id { get; set; }

        public HttpPostedFileBase fileupload { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
