//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopping_cart_details
    {
        public int ID { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string item_price { get; set; }
        public Nullable<int> item_amount { get; set; }
    }
}
