//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopping_cart
    {
        public int ID { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> count { get; set; }
        public string total_amount { get; set; }
    }
}
