//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Details
    {
        public int ID { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> supplier_product_categroy { get; set; }
        public string supplier_product_name { get; set; }
        public string supplier_prd_price { get; set; }
        public string supplier_prd_desc { get; set; }
        public Nullable<System.DateTime> supplier_prd_date { get; set; }
    }
}
